INSERT OR IGNORE INTO Questions (Id, Category, Text, Choices, CorrectAnswerIndex) VALUES
(1, 'Géographie', 'Quelle est la capitale de la France ?', '["Paris","Marseille","Lyon","Toulouse"]', 0),
(2, 'Histoire', 'Qui était le premier empereur de France ?', '["Napoléon Bonaparte","Louis XIV","Charles de Gaulle","François Ier"]', 0),
(3, 'Science', 'Quelle est la formule chimique de l''eau ?', '["H2O","CO2","O2","H2SO4"]', 0),
(4, 'Cinéma', 'Qui a réalisé le film "Inception" ?', '["Christopher Nolan","Steven Spielberg","James Cameron","Martin Scorsese"]', 0),
(5, 'Littérature', 'Qui est l''auteur de "Les Misérables" ?', '["Victor Hugo","Albert Camus","Gustave Flaubert","Émile Zola"]', 0),
(6, 'Musique', 'Qui est connu comme le "Roi de la Pop"?', '["Michael Jackson","Elvis Presley","Prince","Madonna"]', 0),
(7, 'Géographie', 'Quel est le plus long fleuve du monde ?', '["Le Nil","L''Amazone","Le Yangtsé","Le Mississippi"]', 1),
(8, 'Sciences', 'Quel est le symbole chimique pour l''or ?', '["Au","Ag","O","Fe"]', 0),
(9, 'Littérature', 'Quel écrivain a créé le personnage de Sherlock Holmes ?', '["Arthur Conan Doyle","Agatha Christie","Ian Fleming","Stephen King"]', 0),
(10, 'Cinéma', 'Dans quel film pouvez-vous entendre la réplique : "Je suis ton père" ?', '["Star Wars","Le Seigneur des Anneaux","Harry Potter","Le Parrain"]', 0),
(11, 'Histoire', 'Dans quelle ville les accords de paix de 1995 qui ont mis fin à la guerre de Bosnie ont-ils été signés ?', '["Paris","Genève","Dayton","Oslo"]', 2),
(12, 'Musique', 'Quelle est la chanson la plus célèbre de Queen ?', '["Bohemian Rhapsody","We Will Rock You","Another One Bites the Dust","Radio Ga Ga"]', 0),
(13, 'Cuisine', 'Quel est l''ingrédient principal du guacamole ?', '["Avocat","Tomate","Poivron","Oignon"]', 0),
(14, 'Science', 'Quelle planète est connue comme la "planète rouge"?', '["Mars","Jupiter","Vénus","Mercure"]', 0),
(15, 'Technologie', 'Quel est le langage de programmation principalement utilisé pour le développement d''Android ?', '["Java","Swift","C#","Kotlin"]', 3),
(16, 'Sport', 'Quel pays a remporté la Coupe du monde de football en 2018 ?', '["Brésil","Allemagne","France","Argentine"]', 2),
(17, 'Art', 'Qui a peint la Joconde ?', '["Léonard de Vinci","Michel-Ange","Raphaël","Donatello"]', 0),
(18, 'Nature', 'Quel est le mammifère le plus grand sur Terre ?', '["L''éléphant","La baleine bleue","Le rhinocéros","L''hippopotame"]', 1),
(19, 'Astronomie', 'Quelle est l''étoile la plus proche de la Terre ?', '["Le Soleil","Proxima Centauri","Sirius","Alpha Centauri"]', 0),
(20, 'Littérature', 'Qui a écrit "Le Petit Prince"?', '["Antoine de Saint-Exupéry","Ernest Hemingway","Jules Verne","Marcel Proust"]', 0),
(21, 'Gastronomie', 'Dans quelle région de France trouve-t-on la quiche lorraine ?', '["Alsace","Lorraine","Bretagne","Normandie"]', 1),
(22, 'Cinéma', 'Qui a réalisé "Le Fabuleux Destin d''Amélie Poulain"?', '["Jean-Pierre Jeunet","Luc Besson","François Truffaut","Jean-Luc Godard"]', 0),
(23, 'Politique', 'Qui était le président de la France en 2000 ?', '["François Mitterrand","Jacques Chirac","Nicolas Sarkozy","Emmanuel Macron"]', 1),
(24, 'Mythologie', 'Qui est le dieu grec de la guerre ?', '["Zeus","Apollon","Arès","Hermès"]', 2),
(25, 'Langue', 'Que signifie "Renaissance"?', '["Rebirth","Reformation","Rediscovery","Revolution"]', 0);

